<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NBomber" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/OrderSaga.Contracts/OrderSaga.Contracts.csproj" />
  </ItemGroup>

</Project>
