using System.Globalization;
using DotNet.Testcontainers.Containers;
using Npgsql;
using Testcontainers.PostgreSql;
using Testcontainers.RabbitMq;

namespace OrderSaga.IntegrationTests;

/// <summary>
/// Real Postgres and a real RabbitMQ, shared by every test in the suite.
/// </summary>
/// <remarks>
/// <para>
/// The behaviour under test is the behaviour a stand-in gets wrong. An in-memory bus does not redeliver on
/// a consumer crash, and an in-memory database does not enforce the unique constraint that is the actual
/// idempotency mechanism. Both would make this suite fast and worthless.
/// </para>
/// <para>
/// Each test gets four fresh databases and its own broker virtual host. The virtual host matters more than
/// it looks: MassTransit publishes to per-message-type exchanges, so two tests sharing a broker would
/// deliver each other's events into each other's queues and fail in ways that look like saga bugs.
/// </para>
/// </remarks>
public sealed class ContainerFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder("postgres:18-alpine")
        .WithDatabase("postgres")
        .WithUsername("saga")
        .WithPassword("saga")

        // The suite creates four databases per test, and every one of them gets its own connection pool
        // because the connection string differs. The default ceiling of 100 is reached well before the
        // suite finishes.
        .WithCommand("-c", "max_connections=400")
        .Build();

    private readonly RabbitMqContainer _rabbit = new RabbitMqBuilder("rabbitmq:4-management-alpine")
        .WithUsername("saga")
        .WithPassword("saga")
        .Build();

    /// <inheritdoc />
    public async ValueTask InitializeAsync() =>
        await Task.WhenAll(_postgres.StartAsync(), _rabbit.StartAsync());

    /// <inheritdoc />
    public async ValueTask DisposeAsync()
    {
        await _postgres.DisposeAsync();
        await _rabbit.DisposeAsync();
    }

    /// <summary>Creates an empty database and returns a connection string for it.</summary>
    /// <param name="name">Database name. Must be unique within the run.</param>
    public async Task<string> CreateDatabaseAsync(string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        string sanitized = Sanitize(name);

        await using var connection = new NpgsqlConnection(_postgres.GetConnectionString());
        await connection.OpenAsync();

        await using (NpgsqlCommand command = connection.CreateCommand())
        {
            // Identifiers cannot be parameterised. The name is generated by the suite, never user input,
            // and is stripped to characters that cannot terminate the quoted identifier.
            command.CommandText = $"""CREATE DATABASE "{sanitized}" """;
            await command.ExecuteNonQueryAsync();
        }

        return new NpgsqlConnectionStringBuilder(_postgres.GetConnectionString())
        {
            Database = sanitized,

            // Capped, because every test creates four fresh databases and therefore four fresh pools, and
            // the default of a hundred each runs the server out of slots long before the suite ends. Not
            // capped too far: a service starved of connections fails inside a consumer, the broker retries
            // it into the error queue, and the resulting lost message looks exactly like a saga bug.
            MaxPoolSize = 15,
        }.ToString();
    }

    /// <summary>Creates a broker virtual host and returns a connection URI scoped to it.</summary>
    /// <param name="name">Virtual host name. Must be unique within the run.</param>
    public async Task<string> CreateVirtualHostAsync(string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        string sanitized = Sanitize(name);

        await ExecAsync("rabbitmqctl", "add_vhost", sanitized);
        await ExecAsync("rabbitmqctl", "set_permissions", "-p", sanitized, "saga", ".*", ".*", ".*");

        var connection = new Uri(_rabbit.GetConnectionString());

        return string.Create(
            CultureInfo.InvariantCulture,
            $"amqp://saga:saga@{connection.Host}:{connection.Port}/{sanitized}");
    }

    private async Task ExecAsync(params string[] command)
    {
        ExecResult result = await _rabbit.ExecAsync(command);

        if (result.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"'{string.Join(' ', command)}' failed with {result.ExitCode}: {result.Stderr}");
        }
    }

    private static string Sanitize(string name) =>
        new([.. name.Where(static character => char.IsAsciiLetterOrDigit(character) || character == '_')]);
}

/// <summary>Binds the container fixture to every collection that needs infrastructure.</summary>
[CollectionDefinition(Name)]
public sealed class InfrastructureFixtureBinding : ICollectionFixture<ContainerFixture>
{
    /// <summary>Collection name.</summary>
    public const string Name = "infrastructure";
}
